### ISSUE TITLE
Multiuploader überschreibt REDAXO Styles

### ISSUE THREAD

**Issue by ghost** [FriendsOfREDAXO/multiupload#19]
Hier an dieser Stelle werden die Standard REDAXO Styles global überschrieben: https://github.com/FriendsOfREDAXO/multiupload/blob/master/assets/fileuploader.css#L12-L16
Dadurch sind die Button z.B. in einem Einstellungs-Formular nicht mehr korrkt alignt. Bitte diesen Style nur auf den großen Multiupload Button anwenden und nicht auf alle REDAXO Formulare.

**Comment by ghost** [comment]
Das hilft schon mal:

```css
.qq-uploader .rex-form-aligned,
.qq-uploader .btn-toolbar .rex-form-aligned
{
    margin: 0;
}
```
